version: '3.1'
services:
    mongodb:
        image : mongo
        container_name: mongodb
        volumes:
            - /home/rafamagalhas/projects/databases/mongodb:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped